ARG ARTHUR_VERSION

FROM grimoirelab/arthur:$ARTHUR_VERSION

ENTRYPOINT [\
  "/bin/sh", "-c", \
  "python3 bin/arthurd --no-daemon --host ${ARTHUR_HOST} --port ${ARTHUR_PORT} --database ${ARTHUR_DATABASE} --archive-path /archives --log-path ${ARTHUR_LOGS_DIR}"\
  ]
